use_frameworks!

platform :ios, '9.0'

inhibit_all_warnings!

target 'OLCore_Example' do
  use_frameworks!
  
  pod 'SwiftLint'
  pod 'OLCore', :path => '../', :inhibit_warnings => false

  target 'OLCore_Tests' do
    inherit! :search_paths
    
  end
end
